slug: freqtrade-addon
name: Freqtrade Addon
description: A Home Assistant addon for running Freqtrade.
version: 1.0.0
startup: services
panel: true
logo: logo.png
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  telegram_enabled:
    name: Telegram Enabled
    description: Enable Telegram notifications.
    required: false
    default: false
    type: boolean
  telegram_token:
    name: Telegram Token
    description: The token for your Telegram bot.
    required: false
  telegram_chat_id:
    name: Telegram Chat ID
    description: The ID of the Telegram chat where you want to receive notifications.
    required: false
  web_enabled:
    name: Web UI Enabled
    description: Enable the web UI.
    required: false
    default: true
    type: boolean
  web_port:
    name: Web Port
    description: The port for the web UI.
    required: true
    default: 8080
    type: integer
  websocket_enabled:
    name: WebSocket API Enabled
    description: Enable the WebSocket API.
    required: false
    default: true
    type: boolean
  websocket_port:
    name: WebSocket Port
    description: The port for the WebSocket API.
    required: true
    default: 8765
    type: integer
  api_enabled:
    name: REST API Enabled
    description: Enable the REST API.
    required: false
    default: true
    type: boolean
  dry_run:
    name: Dry Run
    description: Run Freqtrade in dry run mode.
    required: false
    default: false
    type: boolean
  freqtrade_config_path:
    name: Freqtrade Config Path
    description: The path to the Freqtrade configuration file.
    required: false
    default: /config/freqtrade/user_data/config.json
  freqtrade_logs_path:
    name: Freqtrade Logs Path
    description: The path to the Freqtrade logs directory.
    required: false
    default: /config/freqtrade/user_data/logs
  freqtrade_data_path:
    name: Freqtrade Data Path
    description: The path to the Freqtrade data directory.
    required: false
    default: /config/freqtrade/user_data/data
  freqtrade_strategy_path:
    name: Freqtrade Strategy Path
    description: The path to the Freqtrade strategy directory.
    required: false
    default: /config/freqtrade/user_data/strategies
  freqtrade_trades_path:
    name: Freqtrade Trades Path
    description: The path to the Freqtrade trades directory.
    required: false
    default: /config/freqtrade/user_data/trades
schema:
  telegram_enabled:
    type: boolean
  telegram_token:
    type: string
  telegram_chat_id:
    type: string
  web_enabled:
    type: boolean
  web_port:
    type: integer
  websocket_enabled:
    type: boolean
  websocket_port:
    type: integer
  api_enabled:
    type: boolean
  dry_run:
    type: boolean
  freqtrade_config_path:
    type: string
  freqtrade_logs_path:
    type: string
  freqtrade_data_path:
    type: string
  freqtrade_strategy_path:
    type: string
  freqtrade_trades_path:
    type: string
env_vars:
  TELEGRAM_ENABLED:
    type: boolean
    required: false
  TELEGRAM_TOKEN:
    type: string
    required: false
  TELEGRAM_CHAT_ID:
    type: string
    required: false
  WEB_ENABLED:
    type: boolean
    required: false
  WEB_PORT:
    type: integer
    required: false
  WEBSOCKET_ENABLED:
    type: boolean
    required: false
  WEBSOCKET_PORT:
    type: integer
    required: false
  API_ENABLED:
    type: boolean
    required: false
  DRY_RUN:
    type: boolean
    required: false
  FREQTRADE_CONFIG_PATH:
    type: string
    required: false
  FREQTRADE_LOGS_PATH:
    type: string
    required: false
  FREQTRADE_DATA_PATH:
    type: string
    required: false
  FREQTRADE_STRATEGY_PATH:
    type: string
    required: false
  FREQTRADE_TRADES_PATH:
    type: string
    required: false
data:
  logo: "https://raw.githubusercontent.com/freqtrade/freqtrade/stable/docs/assets/logo/freqtrade-logo.png"
  # env_vars:
  #   - name: "TZ"
  #     value: "{{ timezone }}"
  #   - name: "TELEGRAM_TOKEN"
  #     value: "{{ TELEGRAM_TOKEN }}"
  #   - name: "TELEGRAM_CHAT_ID"
  #     value: "{{ TELEGRAM_CHAT_ID }}"
  #   - name: "WEB_ENABLED"
  #     value: "{{ WEB_ENABLED }}"
  #   - name: "WEB_PORT"
  #     value: "{{ WEB_PORT }}"
  #   - name: "WEBSOCKET_ENABLED"
  #     value: "{{ WEBSOCKET_ENABLED }}"
  #   - name: "WEBSOCKET_PORT"
  #     value: "{{ WEBSOCKET_PORT }}"
  #   - name: "API_ENABLED"
  #     value: "{{ API_ENABLED }}"
  #   - name: "DRY_RUN"
  #     value: "{{ DRY_RUN }}"
  #   - name: "FREQTRADE_CONFIG_PATH"
  #     value: "{{ FREQTRADE_CONFIG_PATH }}"
  #   - name: "FREQTRADE_LOGS_PATH"
  #     value: "{{ FREQTRADE_LOGS_PATH }}"
  #   - name: "FREQTRADE_DATA_PATH"
  #     value: "{{ FREQTRADE_DATA_PATH }}"
  #   - name: "FREQTRADE_STRATEGY_PATH"
  #     value: "{{ FREQTRADE_STRATEGY_PATH }}"
  #   - name: "FREQTRADE_TRADES_PATH"
  #     value: "{{ FREQTRADE_TRADES_PATH }}"
  ingress:
    - host: "{{ addon_slug }}.local"
      path: /
      port: "{{ WEB_PORT }}"
    - host: "{{ addon_slug }}.{{ domain }}"
      path: /
      port: "{{ WEB_PORT }}"
  options:
    dns: "{{ dns }}"
    privileges: "{{ privileges }}"
    host_network: "{{ host_network }}"
    apparmor: "{{ apparmor }}"
    capabilities: "{{ capabilities }}"
    devices: "{{ devices }}"
    init: "{{ init }}"
    ipc: "{{ ipc }}"
    pid: "{{ pid }}"
    seccomp: "{{ seccomp }}"
    shm_size: "{{ shm_size }}"
    tmpfs:
      - "{{ FREQTRADE_LOGS_PATH }}"
      - "{{ FREQTRADE_DATA_PATH }}"
      - "{{ FREQTRADE_STRATEGY_PATH }}"
      - "{{ FREQTRADE_TRADES_PATH }}"
  startup: "{{ startup }}"
  log_level: "{{ log_level }}"
  image: "{{ image_name }}:{{ image_tag }}"
  name: "{{ addon_slug }}"

